### ISSUE TITLE
How to insert multiple rows at once using sql`...` ?

### ISSUE THREAD

**Issue by moroshko** [neondatabase/serverless#113]
Given an array of 3 row values, how could I insert all the 3 rows in a single sql command?

```
import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.DATABASE_URL);

const data = [
  ["david", 34],
  ["sam", 12],
  ["jane", 25]
];

// What should `values` be here?

await sql`INSERT INTO users (name, age) VALUES ${values}`
```

**Comment by jawj** [comment]
Your example would look like this:

```typescript
await sql`
  INSERT INTO users (name, age) 
  VALUES 
    (${data[0][0]}, ${data[0][1]}),
    (${data[1][0]}, ${data[1][1]}),
    (${data[2][0]}, ${data[2][1]})
`
```

But this is probably only a good idea if you have a fixed (or at least fixed-length) set of values to insert.

**Comment by andyjy** [comment]
For more complex bulk inserts e.g. of arbitrary row lengths, you might find it useful to use a package like `sql-template-tag`, e.g. for your example using `bulk()` like here: https://www.npmjs.com/package/sql-template-tag#bulk

(I'm familiar with `sql-template-tag` as it's [used + re-exported by the Prisma ORM](https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/raw-queries#tagged-template-helpers), but there may be other similar packages to do the same job.)

**Comment by jawj** [comment]
I'm not sure this package will work here, since our driver (like node-postgres) expects dollar-numbered placeholders.

Look out when doing this sort of thing that you don't exceed the maximum of 65,535 parameters that Postgres can handle. https://klotzandrew.com/blog/postgres-passing-65535-parameter-limit/

**Comment by andyjy** [comment]
TIL about the parameter limit 🙏 

Basic example works at least, here's how to pass a dollar-numbered placeholder string and values array to Neon:

```typescript
import { neon } from "@neondatabase/serverless";
import sqlTemplate from "sql-template-tag";

const neonQuery = neon(process.env.DATABASE_URL);

const query = sqlTemplate`SELECT ${"hello, sql'; injection-safe world"}`;
await neonQuery(query.text, query.values);
```

**Comment by Ariel-Moroshko** [comment]
You can generate the numbered placeholders ($1, $2, etc.) dynamically like this:

```typescript
 const sql = neon(process.env.DATABASE_URL);
  const data = [
    ['david', '34'],
    ['sam', '12'],
    ['jane', '25'],
  ];

  // Creates the string: ($1, $2), ($3, $4), ($5, $6)
  const placeholders = data
    .map((_, rowIndex) => `($${rowIndex * 2 + 1}, $${rowIndex * 2 + 2})`)
    .join(', ');

  const response = await sql(
    `INSERT INTO users (name, age) VALUES ${placeholders}`,
    data.flat(),
  );
```

Note that the second argument to `sql` must be a flattened array (`data.flat()`), as each value will correspond sequentially to the numbered placeholders: the first value matches $1, the second value matches $2, and so on.
