### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by lawrencecchen** [neondatabase/serverless#13]
## Steps to reproduce

Using Next.js app directory

"next": "^13.2.4",
"@neondatabase/serverless": "^0.2.9",

`pnpm dev`

## Environment

MacOS
Node v19.4.0

## Logs, links
```
Import trace for requested module:
../../node_modules/@neondatabase/serverless/index.js
../../node_modules/@neondatabase/serverless/index.mjs
./src/app/app/page.tsx
warn  - ../../node_modules/@neondatabase/serverless/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../node_modules/@neondatabase/serverless/index.js
../../node_modules/@neondatabase/serverless/index.mjs
./src/app/app/page.tsx

../../node_modules/@neondatabase/serverless/index.js
```

**Comment by jawj** [comment]
Thanks. I think I know where the warning is coming from, but I think I also know (see separate issue, #12) why the `dev` command isn't working, and we're working on that.

**Comment by maccman** [comment]
Seeing this too

**Comment by jawj** [comment]
This should be resolved in recent releases of the driver (latest is 0.4.18). Please shout if you're still having a problem, otherwise I'll close the issue soon.
