### ISSUE TITLE
Websocket connection  failed

### ISSUE THREAD

**Issue by IshanKBG** [neondatabase/serverless#17]
Hey guys,
It looks I am unable to connect to neondb locally.
It shows a stacktrace error which says " All attempts to open a WebSocket to connect to the database failed."
I am not sure what;s causing this error as i followed very step on the neon docs.
![Screenshot_2023-05-02_18-51-53](https://user-images.githubusercontent.com/71317082/235681072-c2e0e192-0dcd-416f-bb89-08ef9d3e805f.png)

Here is the code
```ts
 import type { DB } from "kysely-codegen"
import { Pool } from "@neondatabase/serverless"
import { PostgresDialect, Kysely } from "kysely"
export const pool = new Pool({
  connectionString: "<string>"
})

export const db = new Kysely<DB>({
  dialect: new PostgresDialect({ pool })
})
```
I am using kysely and astro for my project
This error is happening locally
The deployment target is cloudflare

**Comment by jawj** [comment]
Hi there. When you say you're connecting locally, do you mean you're using Node? If so, [the link in the error message](https://github.com/neondatabase/serverless#run-on-node) may have the answer?

**Comment by IshanKBG** [comment]
> Hi there. When you say you're connecting locally, do you mean you're using Node? If so, [the link in the error message](https://github.com/neondatabase/serverless#run-on-node) may have the answer?

Yes i am using node
I did follow the step but didn't work out
I will retry again
