### ISSUE TITLE
[Question] question about performance?

### ISSUE THREAD

**Issue by shiyuhang0** [neondatabase/serverless#21]
We can connect to Neon with node-pg via TCP or with serverless driver via WebSocket.

I have seen multiple efforts has been made to improve the performance of serverless driver in this blog https://neon.tech/blog/serverless-driver-for-postgres

So, I wonder if there is any performance comparison between node-pg and this serverless driver. thanks!

**Comment by jawj** [comment]
Good question. Not yet, but I expect we'll publish something on this soon.

**Comment by shiyuhang0** [comment]
Excited to see this blog: https://neon.tech/blog/http-vs-websockets-for-postgres-queries-at-the-edge

But should I use the traditional TCP connection via node-pg or serverless-driver in serverless function which supports both? Could you please give me some advice?
