### ISSUE TITLE
>0.4.4 breaks exports.

### ISSUE THREAD

**Issue by alexanderniebuhr** [neondatabase/serverless#24]
All versions above 0.4.3 do not work. Only 0.4.3 works.

## Expected result

Usable Pool & Client exports

## Actual result

```
Pool is not a constructor
```

**Comment by jawj** [comment]
Thanks for your report. I'm assuming that 0.4.9 doesn't fix this? Could you clarify the context that you're seeing this in (e.g. Cloudflare Worker, Node/version, etc)?

**Comment by alexanderniebuhr** [comment]
Yeah, no 0.4.9 does not fix it. It is in a Cloudflare Pages Function -> so Cloudflare Worker.
I did not time to investigate further, in the Editor I can jump to the reference and see the class constructor with all versions. However in runtime it does throw the error. I used to get this a lot with native pg years ago, so I tried to downgrade and see if it is the package or any major issue with my update. Since v0.4.3 works, I expect something changed or broke. Might also be that my setup is incompatible. I can share the full repo (if you want) but it is not isolated reproduction.

**Comment by jawj** [comment]
OK. I just checked our Cloudflare Worker demo with the latest version (0.4.9) and that seems to work fine: https://github.com/neondatabase/serverless-cfworker-demo

I must admit I've not looked at Cloudflare Pages Functions, so I don't know if there's some difference there. If you could share the failing code, that would certainly be helpful.

**Comment by jawj** [comment]
Actually, just realized #19 appears to be the same error with a repro, so I may not need your code just yet ...

**Comment by alexanderniebuhr** [comment]
Thanks. Let me know if you need any more input from my side.

**Comment by jawj** [comment]
I've just released 0.4.10, which I believe fixes this issue. Please do confirm either way.
