### ISSUE TITLE
httpQuery is broken in cloudflare workers. 

### ISSUE THREAD

**Issue by nicksrandall** [neondatabase/serverless#35]
httpQuery does not work in Cloudflare worker because they do not support the `cache` parameter in fetch.

**Comment by nicksrandall** [comment]
see: https://github.com/cloudflare/workerd/issues/698

**Comment by jawj** [comment]
Thanks: I've reverted this change in version 0.5.5 while we figure out how to handle this.

**Comment by jawj** [comment]
OK, this is back in 0.5.6, but we now check that `cache: 'no-store'` is safe (in a `try/catch` block) first.
