### ISSUE TITLE
No such module

### ISSUE THREAD

**Issue by jnthnclrk** [neondatabase/serverless#46]
## Noob question…

I'm prob doing this wrong, but why won't my Cloudflare worker recognise this Neon module? I connected Neon no probs using the integration option…

`import { Client } from '@neondatabase/serverless';`

<img width="500" alt="Screenshot 2023-08-28 at 5 31 21 PM" src="https://github.com/neondatabase/serverless/assets/498192/282c0c09-dee3-4754-aadb-5301009716cf">

This import line is reference in a lot of CF worker Neon docs: https://developers.cloudflare.com/workers/databases/native-integrations/neon/

**Comment by TimoWilhelm** [comment]
You'll probably need to bundle your worker code before depoying it to Cloudflare.
Are you using [Wrangler]((https://developers.cloudflare.com/workers/wrangler/bundling/) to deploy your worker?

**Comment by jnthnclrk** [comment]
Right, so you can't just key import statements into the CF UI?

**Comment by TimoWilhelm** [comment]
Probably not. It would not resolve dependencies from NPM. I'd reccomend following the [Getting Started Guide](https://developers.cloudflare.com/workers/get-started/guide/) on developing with the wrangler CLI.

**Comment by jawj** [comment]
Thanks @TimoWilhelm. Indeed — to import npm packages, you need to be bundling your functions with `wrangler`.
