### ISSUE TITLE
Broken links pointing to non-existing parts of the README

### ISSUE THREAD

**Issue by Jolg42** [neondatabase/serverless#49]
In the source code, you will find these 2 links in error messages:

- https://github.com/neondatabase/serverless/blob/b319c6649b9e42a1d40dba713f9154c6ee1ba069/shims/net/index.ts#L157
- https://github.com/neondatabase/serverless/blob/b319c6649b9e42a1d40dba713f9154c6ee1ba069/shims/net/index.ts#L250

They point to the README, but the headline they are pointing to doesn't seem to exist anymore?

(at Prisma we use a URL shortener where we can update the link it points to for that use-case)

**Comment by jawj** [comment]
Thanks @Jolg42.

The first error message won't often be thrown any more (because a default proxy address is always set), but the second one will be. I've updated the links, so they'll be in the next package version.

**Comment by janpio** [comment]
It looks to me that the `All attempts...` message is also thrown when no `neonConfig.webSocketConstructor` is set when using Node. (Latest published version still uses https://github.com/neondatabase/serverless#run-on-node)

**Comment by jawj** [comment]
Thanks Jan. I wasn't sure this was important enough to make a release for, so I was just going to include this update in the next release.
