### ISSUE TITLE
Cryptic prepared statement errors

### ISSUE THREAD

**Issue by ffxsam** [neondatabase/serverless#53]
## Steps to reproduce
Unknown (error is sporadic)

## Expected result
???

## Actual result
Randomly, I'm seeing cryptic errors like this:
```
|  Error: DB error: ERROR: prepared statement "s996" does not exist

Caused by:
    ERROR: prepared statement "s996" does not exist
   NeonDbError: db error: ERROR: prepared statement "s996" does not exist
```
Then if I reload our app, it runs just fine (with no code changes).

## Environment
Node.js 18.x, Lambda, [SST](https://sst.dev/), working locally (SST dev mode)

**Comment by davidchalifoux** [comment]
I'm also experiencing these errors.
I'm wondering if it's because I'm using a pooled connection string.

**Comment by ffxsam** [comment]
@davidchalifoux I was advised not to use the pooled connection (for now), and to use `neonConfig` to set this:

```ts
import { neon, neonConfig } from '@neondatabase/serverless';

neonConfig.fetchConnectionCache = true;
```

**Comment by jawj** [comment]
@conradludgate Am I right in thinking that the latest pgbouncer is now rolled out in production, and is expected to stop this happening?

**Comment by jawj** [comment]
I believe that deployment of the latest pgbouncer some time ago should have fixed this. Please reopen if that's not the case.
