### ISSUE TITLE
How to type (if posible) a `sql` query response ?

### ISSUE THREAD

**Issue by daguitosama** [neondatabase/serverless#59]
Im reading the examples and documentation on how to use the `client` you get out of `neon(DB_URL)`; but have not found any clear way to type the result of runing a query, like for instance, the way `postgres.js` folks do it:

```ts

type User = {username: string, id: number};

const rows = await sql<User[]>`select * from users;`;
// now TS knows what's comming back of the query on those rows
```
**Is posible doing that typing ?**

If not, i think would be a wonderful adition 😂

**Comment by jawj** [comment]
Currently this is not supported.

However, you could use a tool like Kysely, Zapatos or Drizzle on top of the driver to achieve this.

**Comment by robreiss** [comment]
I just wrote a quick hack. It probably breaks down during edge cases (arrayMode etc), but worked for the couple db calls I do from the edge. 

```sql
import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.NEON_DB_URL!);

export async function sqlNeon<T>(
  query: TemplateStringsArray,
  ...params: any[]
): Promise<T> {
  const result = await sql(query, ...params);
  return result as T;
}
```
