### ISSUE TITLE
Password authentication failed for user 'X' while using connection string in 0.8.0

### ISSUE THREAD

**Issue by zolboo-gtn** [neondatabase/serverless#61]
## Steps to reproduce
Upgrade version to 0.8.0 and use as below.

`new Pool({ connectionString: database.url })`

It works in 0.7.2.

## Expected result
No errors

## Actual result
error: password authentication failed for user 'X'

## Logs, links
-

**Comment by jawj** [comment]
Thanks for filing an issue. We think we know what the problem is here, and should have an update out shortly.

**Comment by jawj** [comment]
OK, 0.8.1 is just published, and should resolve this. It would be much appreciated if you could confirm that it does. I'm guessing you're using a `-pooler` endpoint?

**Comment by zolboo-gtn** [comment]
@jawj 
Thank you for the quick response.
I can confirm that upgrading to 0.8.1 has resolved the issue.
And yes, I'm using pooled connection.
