### ISSUE TITLE
Dependency Installation Failure on Vercel/Cloudflare Edge Runtime

### ISSUE THREAD

**Issue by shreyvarshney1** [neondatabase/serverless#69]
## Steps to reproduce
1. Deploy @neondatabase/serverless on Vercel or Cloudflare.
2. Observe the installation process of dependencies.
3. Encounter the error related to WebSocket dependency installation.

## Expected result
The @neondatabase/serverless should deploy smoothly on Vercel or Cloudflare without any dependency installation issues, including WebSocket.

## Actual result
WebSocket dependency fails to install during deployment on Vercel or Cloudflare, leading to deployment errors.

## Environment
"@neondatabase/serverless": "^0.9.0",
"next": "14.1.3",
"drizzle-orm": "^0.30.2",

#### Cloudflare Pages Logs
https://pastebin.com/yuReHLAh
#### Vercel Logs
https://pastebin.com/wefqysC7

**Comment by jawj** [comment]
Sorry for the late reply.

This package doesn't have any WebSocket library dependency (its [only dependency is `@types/pg`](https://github.com/neondatabase/serverless/blob/main/dist/npm/package.json)).

Perhaps this is an issue with next or drizzle-orm?

**Comment by shreyvarshney1** [comment]
Oh, okay. Then it might be an issue with Drizzle-ORM, as it got fixed when I removed Drizzle from my dev dependencies. It might be the case that dependencies conflicted.
Thanks, I appreciate your attention!
