### ISSUE TITLE
"xxx"(column name) is of type integer but expression is of type text

### ISSUE THREAD

**Issue by ntubrian** [neondatabase/serverless#71]
## Steps to reproduce
Originally, I adopted drizzle-orm, pg, and "@neondatabase/serverless" ,
and try to execute "update multiple rows", in which I'm not sure how to write in the syntax of drizzle-orm
then I followed this post [this post](https://www.answeroverflow.com/m/1113470358964678809)

and do the same thing, (I also create a table on neondb with id and position column (with type int)

then when the query was executed, I got error 
"NeonDbError: column "position" is of type integer but expression is of type text"

and the following script is generated by drizzle-orm
```javascript
update "xxx_schema"."test" set "position" = (case when id = $1 then $2 when id = $3 then $4 when id = $5 then $6 when id = $7 then $8 end) where "test"."id" in ($9, $10, $11, $12) -- params: [2443331299394454528, 0, 2443331317899723776, 1, 2359459378861442048, 2, 2359459369583641600, 3, 2443331299394454528, 2443331317899723776, 2359459378861442048, 2359459369583641600]
```

I have no idea for the type mismatch because the input position value looks like as of integer

-

**Comment by jawj** [comment]
Glad you got this fixed. OK to close this issue then?
